---
title: "Scale Analysis"
output:
  html_document:
    keep_md: no
    toc: yes
    toc_float: true
    code_folding: hide
  word_document:
    keep_md: no
    toc: no
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 4, 
  fig.width = 8, 
  out.width = "650px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 200
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- TRUE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("./analysis/1-first-look/scale-analyis.R")
# read_chunk("../../analysis/1-first-look/new-scale.R") 
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load-packages, echo=echoChunks, message=FALSE, warning=FALSE}
```

<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load-sources, echo=echoChunks, message=FALSE, warning=FALSE}
```

<!-- Load any Global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare-globals, echo=echoChunks, results='show', message=FALSE, warning=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.Suppress the output. --> 
```{r, echo=echoChunks,message=FALSE}
#Put code in here.  It doesn't call a chunk in the codebehind file.
```

<!-- Load the datasets.   -->
```{r load-data, echo=echoChunks, results='show', message=FALSE, warning=FALSE}
```

<!-- Inspect the datasets.   -->
```{r inspect-data, echo=echoChunks, results='show', message=FALSE, warning=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak-data, echo=echoChunks, results='hide', message=FALSE, eval=T, warning=FALSE}
```

```{r item-distributions, echo=echoChunks, fig.width=10, message=FALSE, warning=FALSE, results='asis', cache=TRUE}
```

# Total scores
```{r total-scores, echo=echoChunks, fig.width=10, message=FALSE, warning=FALSE, results='asis', out.width = "960px", cache=TRUE}
```

# Scale Analysis: New
```{r new-scale, echo=echoChunks, fig.height=18, fig.width=18, message=FALSE, results='asis', out.width = "1200px", cache=TRUE}
```

# Scale Analysis: Existing
```{r old-scale, echo=echoChunks, fig.height=18, fig.width=18, message=FALSE, results='asis', out.width = "1200px", cache=TRUE}
```

# Item labels 
```{r item-labels, echo=echoChunks, fig.height=18, fig.width=18, message=FALSE, results='asis', out.width = "1200px", cache=TRUE}
```
